Fix try_run() of MaxSPIRVVersion.cc failed on MSVC
... due to missing C++ standard compile option.

The error was:
```
Run Build Command(s): C:/Users/hlinjama/AppData/Local/Microsoft/WinGet/Packages/Ninja-build.Ninja_Microsoft.Winget.Source_8wekyb3d8bbwe/ninja.exe -v cmTC_f10a6
[1/2] C:\PROGRA~1\MIB055~1\2022\COMMUN~1\VC\Tools\MSVC\1443~1.348\bin\Hostx64\x64\cl.exe  /nologo /TP  -IC:\LLVM-19\include\LLVMSPIRVLib -IC:\LLVM-19\include /DWIN32 /D_WINDOWS /GR /EHsc  /Zi /Ob0 /Od /RTC1 -MD /showIncludes /FoCMakeFiles\cmTC_f10a6.dir\MaxSPIRVversion.cc.obj /FdCMakeFiles\cmTC_f10a6.dir\ /FS -c C:\Users\hlinjama\ws-pocl\pocl\cmake\MaxSPIRVversion.cc
FAILED: CMakeFiles/cmTC_f10a6.dir/MaxSPIRVversion.cc.obj
C:\PROGRA~1\MIB055~1\2022\COMMUN~1\VC\Tools\MSVC\1443~1.348\bin\Hostx64\x64\cl.exe  /nologo /TP  -IC:\LLVM-19\include\LLVMSPIRVLib -IC:\LLVM-19\include /DWIN32 /D_WINDOWS /GR /EHsc  /Zi /Ob0 /Od /RTC1 -MD /showIncludes /FoCMakeFiles\cmTC_f10a6.dir\MaxSPIRVversion.cc.obj /FdCMakeFiles\cmTC_f10a6.dir\ /FS -c C:\Users\hlinjama\ws-pocl\pocl\cmake\MaxSPIRVversion.cc
C:\LLVM-19\include\llvm/ADT/DenseMapInfo.h(26): error C2429: language feature 'nested-namespace-definition' requires compiler flag '/std:c++17'
C:\LLVM-19\include\llvm/ADT/DenseMapInfo.h(142): warning C4984: 'if constexpr' is a C++17 language extension
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.43.34808\include\optional(11): warning STL4038: The contents of <optional> are available only with C++17 or later.
C:\LLVM-19\include\llvm/ADT/STLForwardCompat.h(46): error C2039: 'optional': is not a member of 'std'
(...)
```