Improve formatter scripts
* Try use the latest clang-format-XX in the PATH.

format-branch.sh failed with following error:
```
/mnt/md1/linehill/ws-pocl-2/pocl/tools/scripts/style.GNU:25:3: error: unknown enumerated scalar
  Enabled:         false
  ^
Error reading /mnt/md1/linehill/ws-pocl-2/pocl/tools/scripts/style.GNU: Invalid argument
Formatting pocld/shared_cl_context.cc
/mnt/md1/linehill/ws-pocl-2/pocl/tools/scripts/style.CPP:26:3: error: unknown enumerated scalar
  Enabled:         false
  ^
Error reading /mnt/md1/linehill/ws-pocl-2/pocl/tools/scripts/style.CPP: Invalid argument
```

Perhaps, due to the `clang-format` (v14) on my system being too old
for the custom style files. There are other formatters in
`clang-format-XX` form in the PATH and using the lates one
(`clang-format-19`) fixes the issue. Change format-branch.sh to use
the latest `clang-format-XX` found in path and, otherwise, fall-back
to `clang-format`.

* Remove duplicated formatter logic.

* Verbose output when formatting C++ sources - not just when formatting
  C sources.