Use the clang builtin names for intrinsics in vload_store_half_f16c.c
This way we don't need to include x86intrin.h which redefines the size_t
typedef which is also defined in pocl_types.h

This fixes the build on i686 and arm:

In file included from /builddir/build/BUILD/pocl-53ef5e89aa99b5e85ad512ff46aa8f38b36acf4f/lib/kernel/vload_store_half_f16c.c:50:
In file included from /usr/lib/clang/5.0.0/include/x86intrin.h:29:
In file included from /usr/lib/clang/5.0.0/include/immintrin.h:32:
In file included from /usr/lib/clang/5.0.0/include/xmmintrin.h:39:
In file included from /usr/lib/clang/5.0.0/include/mm_malloc.h:27:
In file included from /usr/include/stdlib.h:31:
/usr/lib/clang/5.0.0/include/stddef.h:62:23: error: typedef redefinition with different types ('unsigned int' vs 'ulong' (aka 'unsigned long'))
typedef __SIZE_TYPE__ size_t;
                      ^
/builddir/build/BUILD/pocl-53ef5e89aa99b5e85ad512ff46aa8f38b36acf4f/include/pocl_types.h:23:15: note: previous definition is here
typedef ulong size_t;
              ^